---
title: "irene_file"
format: html
editor: visual
---

```{r}

library(tidyverse)
load("data/elections_tidy.rda")
load("data/surveys_tidy.rda")

```


First question

Which party was the winner in the municipalities with more than 100,000 habitants (census) in each of the elections?

```{r}
# Filter
elections <- election_data_tidy
head(elections)
str(elections)

large_municipalities <- elections |>
  filter(censo > 100000)

# Winning parties
winners <- large_municipalities |> 
  group_by(date, municipio) |> 
  slice_max(votes, n = 1, with_ties = FALSE) |> 
  select(date, party_recoded, municipio, censo)

# Number of municipalities won
winners_by_party <- winners |> 
  group_by(date, party_recoded)|> 
  summarize(num_municipalities = n(), .groups = "drop") |> 
  arrange(date, desc(num_municipalities))


```


```{r, fig.height = 8, fig.width = 10}

library(showtext)
font_add_google("Roboto", "roboto")
# Modificar el dataframe para que "date" sea un factor con solo las fechas presentes en los datos
winners$date <- factor(winners$date, levels = unique(winners$date))

# Crear el heatmap con los cambios
ggplot(winners, aes(x = date, y = municipio, fill = party_recoded)) +
  geom_tile(color = "white") +
  scale_fill_manual(
    values = c(
      c(
      "PARTIDO POPULAR" = "#1db4e8",
      "PARTIDO SOCIALISTA OBRERO ESPAÑOL" = "#c30505",
      "OTHER" = "gray60",
      "PODEMOS" = "#a444b4",
      "VOX" = "#83b431",
      "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO" = "darkgreen",
      "CONVERGENCIA I UNIO" = "#1b348a")
      ),
    labels = c(
      "PARTIDO POPULAR" = "PP",
      "PARTIDO SOCIALISTA OBRERO ESPAÑOL" = "PSOE",
      "OTHER" = "OTHER",
      "PODEMOS" = "PODEMOS",
      "VOX" = "VOX",
      "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO" = "PNV",
      "CONVERGENCIA I UNIO" = "CiU"
    )
  ) +
  labs(
    title = "Winning party in municipalities with more than 100,000 habitants",
    x = "Date of election",
    y = "Municipality",
    fill = "Parties"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5, family = "Roboto", margin = margin(b = 20)),
    axis.text.x = element_text(size = 11, family = "Roboto", color = "black"),
    axis.text.y = element_text(size = 11, family = "Roboto", color = "black"),
    legend.title = element_text(size = 11, family = "Roboto", face = "bold"),
    legend.text = element_text(size = 10, family = "Roboto"),
    legend.box.background = element_rect(color = "black", size = 0.5),
    plot.margin = margin(15, 15, 15, 15),
    legend.key.size = unit(1, "lines"),
  ) 


```

```{r, fig.height = 6, fig.width = 10}

general_election_winners <- data.frame(
  date = as.Date(c("2008-03-01", "2011-11-01", "2015-12-01", "2016-06-01", "2019-04-01", "2019-11-01")),
  party_recoded = c(
    "PARTIDO SOCIALISTA OBRERO ESPAÑOL",  # 2008
    "PARTIDO POPULAR",                    # 2011
    "PARTIDO POPULAR",                    # 2015
    "PARTIDO POPULAR",                    # 2016
    "PARTIDO SOCIALISTA OBRERO ESPAÑOL",  #Primera de 2019
    "PARTIDO SOCIALISTA OBRERO ESPAÑOL")  #Segunda de 2019
)

# Crear la columna end_date (inicio de la siguiente legislatura)
general_election_winners$end_date <- as.Date(c(
  "2011-11-01", "2015-12-01", "2016-06-01", "2019-04-01", "2019-11-01", "2019-11-01"
))

# Gráfico con fondo de color para los partidos ganadores en las elecciones generales
ggplot(winners_by_party, aes(x = date, y = num_municipalities, color = party_recoded)) +
  geom_rect(data = general_election_winners,
            aes(xmin = date, xmax = end_date, ymin = -Inf, ymax = Inf, fill = party_recoded),
            alpha = 0.1, inherit.aes = FALSE) +
  geom_line(size = 1) +
  geom_point(size = 3) +  
  scale_color_manual(
    values = c(
      "PARTIDO POPULAR" = "#1db4e8",
      "PARTIDO SOCIALISTA OBRERO ESPAÑOL" = "#c30505",
      "OTHER" = "gray60",
      "PODEMOS" = "#a444b4",
      "VOX" = "#83b431",
      "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO" = "darkgreen",
      "CONVERGENCIA I UNIO" = "#1b348a"
    ),
    labels = c(
      "PARTIDO POPULAR" = "PP",
      "PARTIDO SOCIALISTA OBRERO ESPAÑOL" = "PSOE",
      "OTHER" = "Others",
      "PODEMOS" = "Podemos",
      "VOX" = "Vox",
      "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO" = "PNV",
      "CONVERGENCIA I UNIO" = "CiU"
    ),
  scale_fill_manual(
    values = c(
      "PARTIDO POPULAR" = "#1db4e8",
      "PARTIDO SOCIALISTA OBRERO ESPAÑOL" = "#c30505"
    ),
    labels = c(
      "PARTIDO POPULAR" = "PP",
      "PARTIDO SOCIALISTA OBRERO ESPAÑOL" = "PSOE")
  ) +
  geom_vline(data = general_election_winners, aes(xintercept = as.numeric(date)),
             color = "gray50", linetype = "dashed", size = 0.4) +
  labs(
    title = "Evolution of winning party in municipalities with more than 100,000 habitants",
    x = "Date of Election",
    y = "Number of Municipalities",
    color = "Winner in each municipality",
    fill = "General Election Winner"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold", family = "Roboto", margin = margin(b = 20)),
    axis.text.x = element_text(size = 11, family = "Roboto", color = "black"),
    axis.text.y = element_text(size = 11, family = "Roboto", color = "black"),
    legend.title = element_text(size = 11, family = "Roboto", face = "bold"),
    legend.text = element_text(size = 10, family = "Roboto"),
    legend.box.background = element_rect(color = "black", size = 0.5),
    plot.margin = margin(15, 15, 15, 15),
    legend.key.size = unit(1, "lines"),
  ) 





```


Second question

Which party was the second when the first was the PSOE? And when the first was the PP?


```{r}
ranked_votes <- elections |> 
  group_by(date, municipio) |> 
  arrange(desc(votes)) |> 
  mutate(rank = row_number()) |> 
  ungroup()

# PSOE is first
second_psoe <- ranked_votes |> 
  group_by(date, municipio) |> 
  filter(rank == 1 & party_recoded == "PARTIDO SOCIALISTA OBRERO ESPAÑOL") |> 
  left_join(
    ranked_votes |> 
      filter(rank == 2) |> 
      select(date, municipio, second = party_recoded, votes = votes),
    by = c("date", "municipio")
  ) |> 
  ungroup()

second_psoe_sum <- second_psoe |> 
  group_by(date, second) |> 
  summarize(
    num_municipalities = n(),
    .groups = "drop"
  ) |> 
  arrange(date, desc(num_municipalities))

# PP is first
second_pp <- ranked_votes |> 
  group_by(date, municipio) |> 
  filter(rank == 1 & party_recoded == "PARTIDO POPULAR") |> 
  left_join(
    ranked_votes |> 
      filter(rank == 2) |> 
      select(date, municipio, second = party_recoded, votes = votes),
    by = c("date", "municipio")
  ) |> 
  ungroup()

second_pp_sum <- second_pp |> 
  group_by(date, second) |> 
  summarize(
    num_municipalities = n(),
    .groups = "drop"
  ) |> 
  arrange(date, desc(num_municipalities))

head(second_psoe_sum)
```


```{r, fig.height = 6, fig.width = 10}
second_combined <- bind_rows(
  second_pp_sum %>% mutate(first = "PP"),
  second_psoe_sum %>% mutate(first = "PSOE")
)

second_combined$date <- factor(second_combined$date, levels = unique(second_combined$date))

# Gráfico de barras apiladas con facets
ggplot(second_combined, aes(x = date, y = num_municipalities, fill = second)) +
  geom_bar(stat = "identity", position = "fill", color = "black") +
  scale_fill_manual(
    values = c(
      "PARTIDO POPULAR" = "#1db4e8",
      "PARTIDO SOCIALISTA OBRERO ESPAÑOL" = "#c30505",
      "OTHER" = "gray60",
      "PODEMOS" = "#a444b4",
      "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO" = "darkgreen",
      "BLOQUE NACIONALISTA GALEGO" = "lightblue",
      "CIUDADANOS-PARTIDO DE LA CIUDADANIA" = "orange",
      "VOX" = "#83b431",
      "CONVERGENCIA I UNIO" = "#1b348a",
      "ESQUERRA REPUBLICANA DE CATALUNYA"= "yellow"
    ),
    labels = c(
      "PARTIDO POPULAR" = "PP",
      "PARTIDO SOCIALISTA OBRERO ESPAÑOL" = "PSOE",
      "OTHER" = "Others",
      "PODEMOS" = "Podemos",
      "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO" = "PNV",
      "BLOQUE NACIONALISTA GALEGO" = "BNG",
      "CIUDADANOS-PARTIDO DE LA CIUDADANIA" = "C's",
      "CONVERGENCIA I UNIO" = "CiU",
      "ESQUERRA REPUBLICANA DE CATALUNYA"= "ERC"
    )
  ) +
  labs(
    title = "Second places when PSOE or PP were first",
    x = "Election Date",
    y = "Number of Municipalities",
    fill = "Second Party"
  ) +
  facet_wrap(~ first, scales = "free_y", labeller = labeller(first = c(PP = "PP First", PSOE = "PSOE First"))) +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 14, face = "bold", family = "Roboto"),
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5, family = "Roboto", margin = margin(b = 20)),
    axis.text.x = element_text(size = 11, family = "Roboto", color = "black", angle = 20),
    axis.text.y = element_text(size = 11, family = "Roboto", color = "black"),
    legend.title = element_text(size = 11, family = "Roboto", face = "bold"),
    legend.text = element_text(size = 10, family = "Roboto"),
    legend.box.background = element_rect(color = "black", size = 0.5),
    plot.margin = margin(15, 15, 15, 15),
    legend.key.size = unit(1, "lines")
  ) 

```

```{r, fig.height = 7, fig.width = 12}
library(ggalluvial)

# Recodificar los nombres de los partidos
second_combined <- second_combined %>%
  mutate(
    first = recode(first,
      "PARTIDO POPULAR" = "PP",
      "PARTIDO SOCIALISTA OBRERO ESPAÑOL" = "PSOE",
      "OTHER" = "Others",
      "PODEMOS" = "Podemos",
      "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO" = "PNV",
      "BLOQUE NACIONALISTA GALEGO" = "BNG",
      "CIUDADANOS-PARTIDO DE LA CIUDADANIA" = "C's",
      "CONVERGENCIA I UNIO" = "CiU",
      "ESQUERRA REPUBLICANA DE CATALUNYA" = "ERC"
    ),
    second = recode(second,
      "PARTIDO POPULAR" = "PP",
      "PARTIDO SOCIALISTA OBRERO ESPAÑOL" = "PSOE",
      "OTHER" = "Others",
      "PODEMOS" = "Podemos",
      "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO" = "PNV",
      "BLOQUE NACIONALISTA GALEGO" = "BNG",
      "CIUDADANOS-PARTIDO DE LA CIUDADANIA" = "C's",
      "CONVERGENCIA I UNIO" = "CiU",
      "ESQUERRA REPUBLICANA DE CATALUNYA" = "ERC"
    )) |> 
  filter(!(second == "PNV" | second == "BNG" | second == "ERC"))
  

# Gráfico Alluvial actualizado
ggplot(second_combined, aes(
  axis1 = first, axis2 = second,
  y = num_municipalities, fill = second
)) +
  geom_alluvium(aes(fill = second), width = 1/6) +
  geom_stratum(aes(fill = after_stat(stratum)), width = 1/6, color = "black") +
 geom_text(stat = "stratum", aes(label = after_stat(stratum)), size = 3.5, color = "black", fontface = "bold") +
  scale_fill_manual(
    values = c(
      "PP" = "#1db4e8",
      "PSOE" = "#c30505",
      "Others" = "gray60",
      "Podemos" = "#a444b4",
      "PNV" = "darkgreen",
      "BNG" = "lightblue",
      "C's" = "orange",
      "VOX" = "#83b431",
      "CiU" = "#1b348a",
      "ERC" = "yellow"
    )
  ) +
  labs(
    title = "Flow of municipalities won: First to second party",
    x = "First to Second Party",
    y = "Number of Municipalities",
    fill = "Second Party"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 17, face = "bold", hjust = 0.5, family = "Roboto", margin = margin(b = 20)),
    axis.text.x = element_text(size = 12, family = "Roboto", color = "black"),
    axis.text.y = element_text(size = 12, family = "Roboto", color = "black"),
    axis.title.x = element_text(size = 13),
    axis.title.y = element_text(size = 13),
    legend.title = element_text(size = 13, family = "Roboto", face = "bold"),
    legend.text = element_text(size = 11, family = "Roboto"),
    legend.box.background = element_rect(color = "black", size = 0.5),
    plot.margin = margin(15, 15, 15, 15),
    legend.key.size = unit(1, "lines")
  )




```


