---
title: "pablo_changes"
author: "Pablo Aísa"
format: html
editor: visual
---

Data

```{r}

library(tidyverse)

load("data/elections_tidy.rda")
load("data/surveys_tidy.rda")
```

First question

Which party was the winner in the municipalities with more than 100,000 habitants (census) in each of the elections?

```{r}

# Filter
elections <- election_data_tidy |> 
  group_by(date, municipio, party_recoded) |> 
  mutate(votes_recoded = sum(votes, na.rm = TRUE))

head(elections)
str(elections)

large_municipalities <- elections |>
  filter(censo > 100000)

# Winning parties
winners <- large_municipalities |> 
  group_by(date, municipio) |> 
  slice_max(votes, n = 1, with_ties = FALSE) |> 
  ungroup()

# Number of municipalities won
elections_winners <- winners |> 
  group_by(date, party_recoded)|> 
  summarize(num_municipalities = n(), .groups = "drop") |> 
  arrange(date, desc(num_municipalities))

```

Second question

Which party was the second when the first was the PSOE? And when the first was the PP?

```{r}

ranked_votes <- elections |> 
  group_by(date, municipio) |> 
  arrange(desc(votes)) |> 
  mutate(rank = row_number()) |> 
  ungroup()

# PSOE is first
second_psoe <- ranked_votes |> 
  group_by(date, municipio) |> 
  filter(rank == 1 & party_recoded == "PARTIDO SOCIALISTA OBRERO ESPAÑOL") |> 
  left_join(
    ranked_votes |> 
      filter(rank == 2) |> 
      select(date, municipio, second = party_recoded, votes = votes),
    by = c("date", "municipio")
  ) |> 
  ungroup()

second_psoe_sum <- second_psoe |> 
  group_by(date, second) |> 
  summarize(
    num_municipalities = n(),
    .groups = "drop"
  ) |> 
  arrange(date, desc(num_municipalities))

# PP is first
second_pp <- ranked_votes |> 
  group_by(date, municipio) |> 
  filter(rank == 1 & party_recoded == "PARTIDO POPULAR") |> 
  left_join(
    ranked_votes |> 
      filter(rank == 2) |> 
      select(date, municipio, second = party_recoded, votes = votes),
    by = c("date", "municipio")
  ) |> 
  ungroup()

second_pp_sum <- second_pp |> 
  group_by(date, second) |> 
  summarize(
    num_municipalities = n(),
    .groups = "drop"
  ) |> 
  arrange(date, desc(num_municipalities))

```

Cataluña elections

```{r}
library(dplyr)
library(ggplot2)
library(showtext)

font_add_google("Roboto Condensed", "roboto")

new_parties <- c("JUNTS PER CATALUNYA-JUNTS", 
                 "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA")

catalunya <- election_data_tidy |> 
  mutate(
    party_recoded = case_when(
      party %in% new_parties ~ party,
      TRUE ~ party_recoded
    ),
    siglas = case_when(
      party_recoded == "JUNTS PER CATALUNYA-JUNTS" ~ "CIU",
      party_recoded == "CONVERGÈNCIA DEMOCRÀTICA DE CATALUNYA" ~ "CIU",
      TRUE ~ siglas
    ),
    province = case_when(
      codigo_provincia == "08" ~ "Barcelona",
      codigo_provincia == "17" ~ "Girona",
      codigo_provincia == "25" ~ "Lleida",
      codigo_provincia == "43" ~ "Tarragona",
      TRUE ~ "Unknown"
    )
  ) |> 
  filter(codigo_ccaa == "09") |> 
  distinct(date, cod_mun, party_recoded, .keep_all = TRUE)

catalunya_votes <- catalunya |> 
  group_by(date, province, siglas) |> 
  summarize(total_votes = sum(votes, na.rm = TRUE), .groups = "drop") |> 
  group_by(date, province) |> 
  mutate(
    vote_percentage = (total_votes / sum(total_votes)) * 100
  ) |> 
  ungroup()

g <- ggplot(catalunya_votes, aes(x = date, y = vote_percentage, 
                                 colour = siglas, group = siglas)) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  facet_wrap(~ province, ncol = 2) +
  scale_color_manual(
    values = c(
      "PP" = "#1db4e8",
      "PSOE" = "#c30505",
      "OTHER" = "gray60",
      "PODEMOS" = "#a444b4",
      "VOX" = "#83b431",
      "ERC" = "#ffbf41",
      "CIU" = "#1b348a",
      "MP" = "#004938",
      "CS" = "#eb6109",
      "JUNTS" = "#00c3b3",
      "CDC" = "#1c3687"
    )) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  labs(
    title = "Elections in Catalonia over the years",
    x = "Date of the election",
    y = "Vote Share (%)",
    color = "Party"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5, family = "Roboto", margin = margin(b = 20)),
    axis.text.x = element_text(size = 10, family = "Roboto", color = "black"),
    axis.text.y = element_text(size = 10, family = "Roboto", color = "black"),
    legend.title = element_text(size = 11, family = "Roboto", face = "bold"),
    legend.text = element_text(size = 10, family = "Roboto"),
    legend.box.background = element_rect(color = "black", size = 0.5),
    plot.margin = margin(15, 15, 15, 15),
    legend.key.size = unit(1, "lines")
  )

g
 

```
